# Generated by Django 6.0.5 on 2026-06-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='boby',
            new_name='body',
        ),
    ]
